In [3]:
# if you are using Jupyter notebook execute 1st:
!pip install tensorflow

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
# Dense: to add layers(hidden, output)
from tensorflow.keras import Sequential
# Sequential: to add layers in sequence, to initialize ann model i.e. initially random weight will be assigned
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df # Exited is a target column. Binary Classification problem
# given the customer details, bank want to predict whether customer will leave the bank or not.

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [6]:
# Not important columns
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

# Data Transformation

In [7]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [9]:
df.drop(columns = ['Exited']) # no permanent deletion of Exited column

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [10]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'],dtype = int)  # dtype = int to make encoded values (0,1) permanent
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1                 1   
1                  1        112542.58       0                 0   
2                  0        113931.57       1                 1   
3                  0         93826.63       0                 1   
4                  1         79084.10       0                 0   
...              ...              ...     ...               ...   
9995               0         96270.64       0                 1   
9996               1        101699.77       0                 1   
9997               1         42085.58       1                 1   
9998               0         92888.52       1                 0   
9999               0         38190.78       0                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

# Model Building

In [11]:
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1                 1   
1                  1        112542.58       0                 0   
2                  0        113931.57       1                 1   
3                  0         93826.63       0                 1   
4                  1         79084.10       0                 0   
...              ...              ...     ...               ...   
9995               0         96270.64       0                 1   
9996               1        101699.77       0                 1   
9997               1         42085.58       1                 1   
9998               0         92888.52       1                 0   
9999               0         38190.78       0                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

In [12]:
sc = StandardScaler() # don't perform standardization on target column
x = df.drop(columns=['Exited'])# exclude Exited column
y = df['Exited']

In [13]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [14]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [15]:
xtrain

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [16]:
# create instance of Sequential class or initialize the model
model = Sequential()
# Sequential is a class in Keras that allows you to build ANN model layer-by-layer.
# create neurons in input, hidden and output layers and assign random weights to input
# In I/P layer 13 neurons will be there as there are 13 independent features

#Add hidden layer, randomly 10 neurons are added
model.add(Dense(units=10,activation='relu'))# as target is binary use relu activation
# Layers are added sequentially using the .add() method.
# Each layer receives input from the previous layer and passes output to the next one.

#Add output layer
model.add(Dense(units=1, activation='sigmoid'))# for binary classification use sigmoid activation in output layer

#Establish the connection between the layers
model.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics=['accuracy'])
# adadelta is gradient descent algorithm for weight updation which we have selected randomly. We will hypertune it afterwards
# binary_crossentropy: also called log_loss, finds erros, range is 0 to 1

#Fit the data, perform forward and back propagation
model.fit(xtrain,ytrain, epochs=100)
# epochs=100 means that the model will go through the entire xtrain and ytrain dataset 100 times during training.
# epoch: backward and forward propagation will be done for 100 times
# The number of batches per epoch = Total number of samples / Batch size (default is 32)
# 80% training data = 8000 samples. So Batches=8000/32 = 250
# Each batch is processed in sequence during each epoch,
# and after all 250 batches are processed, one epoch is complete.

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5345 - loss: 0.7761
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5378 - loss: 0.7686
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5500 - loss: 0.7686
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5560 - loss: 0.7635
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5375 - loss: 0.7829
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5471 - loss: 0.7768
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5490 - loss: 0.7679
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5485 - loss: 0.7661
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5516 - loss: 0.7670
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5483 - loss: 0.7746
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5547 - loss: 0.7683
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [17]:
# accuracy is not good and error is also high as hyperparameter tuning is not done
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [18]:
ypred = model.predict(xtest)
ypred # in dataset target column values are 0 or 1, but here output is a continuous number
# because in output layer activation function is sigmoid. It gives you o/p in terms of probability
# In sigmoid if probability is > 0.5 it gives you 1 and if probability < 0 it should give 0

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([[0.57745725],
       [0.26757547],
       [0.34344757],
       ...,
       [0.8478717 ],
       [0.3120598 ],
       [0.41451323]], dtype=float32)

In [19]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [20]:
print(classification_report(ytest,ypred))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [21]:
ypred > 0.5 # not it will give me 1 or 0 OR true or false answers

array([[ True],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [22]:
ypred = ypred > 0.5
ypred

array([[ True],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [23]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [24]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76      1585
           1       0.24      0.33      0.28       415

    accuracy                           0.64      2000
   macro avg       0.52      0.53      0.52      2000
weighted avg       0.69      0.64      0.66      2000



# Hyperparameter Tuning

In [25]:
!pip install -U keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.2 MB/s eta 0:00:00


# **Tuning the ANN Model**
- Selecting the best optimizer




In [26]:
import keras_tuner as kt

In [27]:
# tuning for optimizer(adam,rmsprop or sgd:stochastic gradient descent) only
def optimizer_selection(hp):
    # hp (HyperParameters) is an object used to define search spaces for the hyperparameters you want to tune.
    # This allows the Keras Tuner to explore different values for the hyperparameters
    # and find the best ones during the search.

    #create instance of sequential class
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop']) #value of optimizer is categorical so use choice()function else use hp.Int()
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [28]:
# similar to GridSearchCV() we will use here RandomSearch()
tuner = kt.RandomSearch(
    optimizer_selection,# model name-here Sequential() class is our model
    objective='val_accuracy', # increase accuracy of test data i.e. validation test accuracy or minimize 'val_loss'
    max_trials=3 # for each optimizer take 3 trials: for sgd-3 trials, for adam-3 trials, for rmsprop-3 trials
    # can select 3 to 10 or 20 for larger problems
)

In [29]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))
# tuner.search() is equivalent to grid.fit()
# When we call tuner.search(), we are not directly calling the hyper() function.
# Instead, Keras Tuner automatically calls hyper()
# and passes the hp object to it during the search.
# We don’t manually pass hp as an argument because Keras Tuner handles it behind the scenes.

# epochs should be same as max_trials so 3 is selected
# validation_data: pass test data

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8125

Best val_accuracy So Far: 0.8190000057220459
Total elapsed time: 00h 00m 11s


In [30]:
tuner.get_best_hyperparameters()[0].values # as per performance all optimizers are stored in an array
# we want high accuracy optimizer present at index 0 location

{'optimizer': 'rmsprop'}

In [31]:
model = tuner.get_best_models(num_models=1)[0] # get best model: rmsprop
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8121 - loss: 0.4260 - val_accuracy: 0.8235 - val_loss: 0.4107
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8205 - loss: 0.4165 - val_accuracy: 0.8250 - val_loss: 0.4050
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8196 - loss: 0.4152 - val_accuracy: 0.8275 - val_loss: 0.4008
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8275 - loss: 0.4029 - val_accuracy: 0.8330 - val_loss: 0.3976
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8290 - loss: 0.3974 - val_accuracy: 0.8325 - val_loss: 0.3936
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8258 - loss: 0.4022 - val_accuracy: 0.8320 - val_loss: 0.3907
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8288 - loss: 0.3976 - val_accuracy: 0.8320 - val_loss: 0.3878
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8311 - loss: 0.3880 - val_accu

In [32]:
# In above output we have only hypertuned optimizer and
# we got generalized model having improved accuracy- previously it was 76%
# now we got training accuracy=86.47% and testing accuracy=86.40%
model.evaluate(xtrain,ytrain) # same as score() function


250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8640 - loss: 0.3359


[0.33516591787338257, 0.8613749742507935]

In [33]:
model.evaluate(xtest,ytest)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8579 - loss: 0.3428


[0.3333280086517334, 0.859000027179718]

# Regression

In [34]:
df = pd.read_csv('/content/Price.csv')
df

price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [35]:
x = df.iloc[:,1:]
y = df['price']

In [36]:
x = sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [37]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [38]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))# hidden layer1
ann.add(Dense(units=20, activation='relu'))# hidden layer2

ann.add(Dense(units=1))# output layer.
#In Regression task no activation function is required in output layer as we don't have to convert price to 0 or 1

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 255232.8906 - val_loss: 262337.0938
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 253623.6719 - val_loss: 261589.5469
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 253798.4531 - val_loss: 260425.3594
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 252600.8125 - val_loss: 258601.5625
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 251290.9062 - val_loss: 255943.2812
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 250927.3906 - val_loss: 252176.0000
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 242504.7500 - val_loss: 247172.8750
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 235436.0781 - val_loss: 240664.2188
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 233539.8438 - val_loss: 232488.2969
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 224094.2969 - val_loss: 222626.2188
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/s

In [39]:
yp = ann.predict(xtest)
yp

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


array([[477.46622],
       [524.1641 ],
       [491.11057],
       [530.8577 ],
       [657.50397],
       [346.39783],
       [379.4655 ],
       [373.95224],
       [717.9902 ],
       [501.0507 ],
       [471.70233],
       [506.0153 ],
       [492.60126],
       [365.90738],
       [546.76276],
       [494.31363],
       [576.2111 ],
       [548.1795 ],
       [480.06155],
       [498.46683],
       [470.38705],
       [597.9605 ],
       [438.5228 ],
       [580.8551 ],
       [422.43094],
       [520.72534],
       [385.0397 ],
       [503.16376],
       [541.78644],
       [345.0722 ],
       [433.96118],
       [637.9538 ],
       [559.96204],
       [535.31195],
       [607.7275 ],
       [542.3593 ],
       [402.52283],
       [572.31305],
       [581.6243 ],
       [513.5557 ],
       [422.34598],
       [732.2161 ],
       [523.4196 ],
       [530.0464 ],
       [511.38983],
       [459.8296 ],
       [518.8062 ],
       [528.3276 ],
       [587.0307 ],
       [464.84274],


In [40]:
from sklearn.metrics import r2_score # accuracy metric for regression task is r squared

In [41]:
r2_score(ytest,yp)

0.9561180556947192